### PR TITLE
index_change_1.2

### PR DESCRIPTION
**Pull request by varg-21**
Index page fixed.

### CODE REVIEW

**Comment by varg-21** [comment]
Change reviewed.

**Comment by varg-21** [comment]
Index page fix

**Review by varg-21 — COMMENTED** [review]
Change reviewed

**Review by varg-21 — COMMENTED** [review]
Changes reviewed

**Comment by varg-21** [comment]
Change 1.2 reviewed

**Comment by varg-21** [comment]
Merge accepted

**Review by varg-21 — COMMENTED** [review]
Reviewed

**Comment by riggi-21** [comment]
The more recent version is available. Request ignored.

**Comment by varg-21** [comment]
Ignored.

**Pull request closed without merging**
